services:
  - type: web
    name: doksan-plus
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn doksan_plus.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: API_FOOTBALL_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: PYTHONPATH
        value: /opt/render/project/src 