# Generated by Django 5.2.1 on 2025-05-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skorlar', '0002_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_tr',
            field=models.CharField(default='A seçeneği (TR)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_tr',
            field=models.CharField(default='B seçeneği (TR)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_tr',
            field=models.TextField(default='Soru metni (TR)'),
            preserve_default=False,
        ),
    ]
